In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import json
import random
import pandas as pd

In [ ]:
import os
import random

# 1. Point to your Google Drive folder
# Update this string to match the exact folder name where you saved the files in Drive
data_dir = "/content/drive/MyDrive/JSON"
all_files = [f for f in os.listdir(data_dir) if f.endswith('.json')]

# Randomly sample 1000 patients, or fewer if not enough are available
random.seed(42)
sampled_files = random.sample(all_files, min(len(all_files), 1000))

NameError: name 'os' is not defined

In [ ]:
# 2. Extract specific resources (e.g., Observations)
observations_data = []
for file_name in sampled_files:
    file_path = os.path.join(data_dir, file_name)
    with open(file_path, 'r') as f:
        fhir_bundle = json.load(f)

        # Check if 'entry' exists in the bundle
        if 'entry' in fhir_bundle:
            for entry in fhir_bundle['entry']:
                resource = entry.get('resource', {})

                # Filter for the specific resource type
                if resource.get('resourceType') == 'Observation':
                    observations_data.append(resource)

In [ ]:
# 3. Flatten the nested JSON into a clean, tabular format
df_observations = pd.json_normalize(observations_data)

# 4. Save the CSV directly to your Drive so it is permanently stored
output_path = "/content/drive/MyDrive/flattened_observations.csv"
df_observations.to_csv(output_path, index=False)

print(f"Flattened {len(df_observations)} observations into tabular format. Saved to {output_path}.")

Flattened 5134 observations into tabular format. Saved to /content/drive/MyDrive/flattened_observations.csv.

In [ ]:
import pandas as pd
import numpy as np
import ast

In [ ]:
df = pd.read_csv('flattened_observations.csv')

print("Original Shape:", df.shape)

Original Shape: (5134, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5134 entries, 0 to 5133
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5134 non-null   object
 1   status                       5134 non-null   object
 2   effectiveDateTime            5134 non-null   object
 3   resourceType                 5134 non-null   object
 4   code.coding                  5134 non-null   object
 5   subject.reference            5134 non-null   object
 6   encounter.reference          5134 non-null   object
 7   valueQuantity.value          4493 non-null   float64
 8   valueQuantity.unit           4493 non-null   object
 9   valueQuantity.system         4493 non-null   object
 10  valueQuantity.code           4493 non-null   object
 11  component                    630 non-null    object
 12  valueCodeableConcept.coding  11 non-null     object
dtypes: float64(1), object(12)
memory usage: 521.6+ KB

In [ ]:
# Remove duplicates
df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (5134, 13)

In [ ]:
df.head()

,id,status,effectiveDateTime,resourceType,code.coding,subject.reference,encounter.reference,valueQuantity.value,valueQuantity.unit,valueQuantity.system,valueQuantity.code,component,valueCodeableConcept.coding
0,cab2e694-f24b-4409-a71e-8e109b5229bb,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '4548-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,5.90000,%,http://unitsofmeasure.org/,%,NaN,NaN
1,0017cb31-e3b5-4167-a513-c0e99a1e8056,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '8302-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,174.66385,cm,http://unitsofmeasure.org/,cm,NaN,NaN
2,a11dcfea-83a0-4588-b60e-62f8dc437512,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '29463...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,97.46566,kg,http://unitsofmeasure.org/,kg,NaN,NaN
3,ef407614-d461-4e7d-b48a-e68165b66580,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '39156...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,31.94814,kg/m2,http://unitsofmeasure.org/,kg/m2,NaN,NaN
4,5a54a97c-67bc-46f4-8619-81971eceaabc,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '55284...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,NaN,NaN,NaN,NaN,[{'code': {'coding': [{'system': 'http://loinc...,NaN

In [ ]:
# Convert datetime
df["effectiveDateTime"] = pd.to_datetime(
    df["effectiveDateTime"],
    errors="coerce"
)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5134 entries, 0 to 5133
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5134 non-null   object
 1   status                       5134 non-null   object
 2   effectiveDateTime            1722 non-null   datetime64[ns, UTC-05:00]
 3   resourceType                 5134 non-null   object
 4   code.coding                  5134 non-null   object
 5   subject.reference            5134 non-null   object
 6   encounter.reference          5134 non-null   object
 7   valueQuantity.value          4493 non-null   float64
 8   valueQuantity.unit           4493 non-null   object
 9   valueQuantity.system         4493 non-null   object
 10  valueQuantity.code           4493 non-null   object
 11  component                    630 non-null    object
 12  valueCodeableConcept.coding  11 non-null     object
dtypes: datetime64[ns, UTC-05:00](1), float64(1), object(11)
memory usage: 521.6+ KB

In [ ]:
# Keep only final observations
if "status" in df.columns:
    df = df[df["status"] == "final"]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5134 entries, 0 to 5133
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5134 non-null   object
 1   status                       5134 non-null   object
 2   effectiveDateTime            1722 non-null   datetime64[ns, UTC-05:00]
 3   resourceType                 5134 non-null   object
 4   code.coding                  5134 non-null   object
 5   subject.reference            5134 non-null   object
 6   encounter.reference          5134 non-null   object
 7   valueQuantity.value          4493 non-null   float64
 8   valueQuantity.unit           4493 non-null   object
 9   valueQuantity.system         4493 non-null   object
 10  valueQuantity.code           4493 non-null   object
 11  component                    630 non-null    object
 12  valueCodeableConcept.coding  11 non-null     object
dtypes: datetime64[ns, UTC-05:00](1), float64(1), object(11)
memory usage: 521.6+ KB

In [ ]:
# Create date features
df["observation_date"] = df["effectiveDateTime"].dt.date
df["year"] = df["effectiveDateTime"].dt.year
df["month"] = df["effectiveDateTime"].dt.month
df["month_name"] = df["effectiveDateTime"].dt.month_name()

# Convert numeric observation values
df["valueQuantity.value"] = pd.to_numeric(
    df["valueQuantity.value"],
    errors="coerce"
)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5134 entries, 0 to 5133
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5134 non-null   object
 1   status                       5134 non-null   object
 2   effectiveDateTime            1722 non-null   datetime64[ns, UTC-05:00]
 3   resourceType                 5134 non-null   object
 4   code.coding                  5134 non-null   object
 5   subject.reference            5134 non-null   object
 6   encounter.reference          5134 non-null   object
 7   valueQuantity.value          4493 non-null   float64
 8   valueQuantity.unit           4493 non-null   object
 9   valueQuantity.system         4493 non-null   object
 10  valueQuantity.code           4493 non-null   object
 11  component                    630 non-null    object
 12  valueCodeableConcept.coding  11 non-null     object
 13  observation_date             1722 non-null   object
 14  year                         1722 non-null   float64
 15  month                        1722 non-null   float64
 16  month_name                   1722 non-null   object
dtypes: datetime64[ns, UTC-05:00](1), float64(3), object(13)
memory usage: 682.0+ KB

In [ ]:
def extract_code_info(code_str):

    try:
        code_list = ast.literal_eval(code_str)

        if isinstance(code_list, list) and len(code_list) > 0:

            first_item = code_list[0]

            return pd.Series({
                "loinc_code": first_item.get("code"),
                "observation_name": first_item.get("display")
            })

    except:
        pass

    return pd.Series({
        "loinc_code": np.nan,
        "observation_name": np.nan
    })


code_details = df["code.coding"].apply(extract_code_info)

df = pd.concat([df, code_details], axis=1)

In [ ]:
df.head()

,id,status,effectiveDateTime,resourceType,code.coding,subject.reference,encounter.reference,valueQuantity.value,valueQuantity.unit,valueQuantity.system,valueQuantity.code,component,valueCodeableConcept.coding,observation_date,year,month,month_name,loinc_code,observation_name
0,cab2e694-f24b-4409-a71e-8e109b5229bb,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '4548-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,5.90000,%,http://unitsofmeasure.org/,%,NaN,NaN,2012-12-28,2012.0,12.0,December,4548-4,Hemoglobin A1c/Hemoglobin.total in Blood
1,0017cb31-e3b5-4167-a513-c0e99a1e8056,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '8302-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,174.66385,cm,http://unitsofmeasure.org/,cm,NaN,NaN,2012-12-28,2012.0,12.0,December,8302-2,Body Height
2,a11dcfea-83a0-4588-b60e-62f8dc437512,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '29463...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,97.46566,kg,http://unitsofmeasure.org/,kg,NaN,NaN,2012-12-28,2012.0,12.0,December,29463-7,Body Weight
3,ef407614-d461-4e7d-b48a-e68165b66580,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '39156...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,31.94814,kg/m2,http://unitsofmeasure.org/,kg/m2,NaN,NaN,2012-12-28,2012.0,12.0,December,39156-5,Body Mass Index
4,5a54a97c-67bc-46f4-8619-81971eceaabc,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '55284...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,NaN,NaN,NaN,NaN,[{'code': {'coding': [{'system': 'http://loinc...,NaN,2012-12-28,2012.0,12.0,December,55284-4,Blood Pressure

In [ ]:
def extract_bp_values(component_str):

    systolic = np.nan
    diastolic = np.nan

    try:
        components = ast.literal_eval(component_str)

        for item in components:

            coding = item.get("code", {}).get("coding", [])

            if len(coding) > 0:

                code = coding[0].get("code")

                value = item.get(
                    "valueQuantity", {}
                ).get("value")

                # Systolic BP
                if code == "8480-6":
                    systolic = value

                # Diastolic BP
                elif code == "8462-4":
                    diastolic = value

    except:
        pass

    return pd.Series({
        "systolic_bp": systolic,
        "diastolic_bp": diastolic
    })


bp_values = df["component"].apply(extract_bp_values)

df = pd.concat([df, bp_values], axis=1)

In [ ]:
df.head()

,id,status,effectiveDateTime,resourceType,code.coding,subject.reference,encounter.reference,valueQuantity.value,valueQuantity.unit,valueQuantity.system,...,component,valueCodeableConcept.coding,observation_date,year,month,month_name,loinc_code,observation_name,systolic_bp,diastolic_bp
0,cab2e694-f24b-4409-a71e-8e109b5229bb,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '4548-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,5.90000,%,http://unitsofmeasure.org/,...,NaN,NaN,2012-12-28,2012.0,12.0,December,4548-4,Hemoglobin A1c/Hemoglobin.total in Blood,NaN,NaN
1,0017cb31-e3b5-4167-a513-c0e99a1e8056,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '8302-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,174.66385,cm,http://unitsofmeasure.org/,...,NaN,NaN,2012-12-28,2012.0,12.0,December,8302-2,Body Height,NaN,NaN
2,a11dcfea-83a0-4588-b60e-62f8dc437512,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '29463...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,97.46566,kg,http://unitsofmeasure.org/,...,NaN,NaN,2012-12-28,2012.0,12.0,December,29463-7,Body Weight,NaN,NaN
3,ef407614-d461-4e7d-b48a-e68165b66580,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '39156...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,31.94814,kg/m2,http://unitsofmeasure.org/,...,NaN,NaN,2012-12-28,2012.0,12.0,December,39156-5,Body Mass Index,NaN,NaN
4,5a54a97c-67bc-46f4-8619-81971eceaabc,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '55284...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,NaN,NaN,NaN,...,[{'code': {'coding': [{'system': 'http://loinc...,NaN,2012-12-28,2012.0,12.0,December,55284-4,Blood Pressure,159.0,104.0

In [ ]:
df["bmi_category"] = None

df.loc[
    (df["observation_name"] == "Body Mass Index") &
    (df["valueQuantity.value"] >= 30),
    "bmi_category"
] = "Obese"

df.loc[
    (df["observation_name"] == "Body Mass Index") &
    (df["valueQuantity.value"] >= 25) &
    (df["valueQuantity.value"] < 30),
    "bmi_category"
] = "Overweight"

df.loc[
    (df["observation_name"] == "Body Mass Index") &
    (df["valueQuantity.value"] < 25),
    "bmi_category"
] = "Normal"

In [ ]:
df.head()

,id,status,effectiveDateTime,resourceType,code.coding,subject.reference,encounter.reference,valueQuantity.value,valueQuantity.unit,valueQuantity.system,...,valueCodeableConcept.coding,observation_date,year,month,month_name,loinc_code,observation_name,systolic_bp,diastolic_bp,bmi_category
0,cab2e694-f24b-4409-a71e-8e109b5229bb,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '4548-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,5.90000,%,http://unitsofmeasure.org/,...,NaN,2012-12-28,2012.0,12.0,December,4548-4,Hemoglobin A1c/Hemoglobin.total in Blood,NaN,NaN,None
1,0017cb31-e3b5-4167-a513-c0e99a1e8056,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '8302-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,174.66385,cm,http://unitsofmeasure.org/,...,NaN,2012-12-28,2012.0,12.0,December,8302-2,Body Height,NaN,NaN,None
2,a11dcfea-83a0-4588-b60e-62f8dc437512,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '29463...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,97.46566,kg,http://unitsofmeasure.org/,...,NaN,2012-12-28,2012.0,12.0,December,29463-7,Body Weight,NaN,NaN,None
3,ef407614-d461-4e7d-b48a-e68165b66580,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '39156...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,31.94814,kg/m2,http://unitsofmeasure.org/,...,NaN,2012-12-28,2012.0,12.0,December,39156-5,Body Mass Index,NaN,NaN,Obese
4,5a54a97c-67bc-46f4-8619-81971eceaabc,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '55284...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,NaN,NaN,NaN,...,NaN,2012-12-28,2012.0,12.0,December,55284-4,Blood Pressure,159.0,104.0,None

In [ ]:
df["high_bp_flag"] = np.where(

    (df["systolic_bp"] >= 140) |
    (df["diastolic_bp"] >= 90),

    1,
    0
)

In [ ]:
df.head()

,id,status,effectiveDateTime,resourceType,code.coding,subject.reference,encounter.reference,valueQuantity.value,valueQuantity.unit,valueQuantity.system,...,observation_date,year,month,month_name,loinc_code,observation_name,systolic_bp,diastolic_bp,bmi_category,high_bp_flag
0,cab2e694-f24b-4409-a71e-8e109b5229bb,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '4548-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,5.90000,%,http://unitsofmeasure.org/,...,2012-12-28,2012.0,12.0,December,4548-4,Hemoglobin A1c/Hemoglobin.total in Blood,NaN,NaN,None,0
1,0017cb31-e3b5-4167-a513-c0e99a1e8056,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '8302-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,174.66385,cm,http://unitsofmeasure.org/,...,2012-12-28,2012.0,12.0,December,8302-2,Body Height,NaN,NaN,None,0
2,a11dcfea-83a0-4588-b60e-62f8dc437512,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '29463...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,97.46566,kg,http://unitsofmeasure.org/,...,2012-12-28,2012.0,12.0,December,29463-7,Body Weight,NaN,NaN,None,0
3,ef407614-d461-4e7d-b48a-e68165b66580,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '39156...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,31.94814,kg/m2,http://unitsofmeasure.org/,...,2012-12-28,2012.0,12.0,December,39156-5,Body Mass Index,NaN,NaN,Obese,0
4,5a54a97c-67bc-46f4-8619-81971eceaabc,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '55284...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,NaN,NaN,NaN,...,2012-12-28,2012.0,12.0,December,55284-4,Blood Pressure,159.0,104.0,None,1

In [ ]:
df["diabetes_risk"] = None

df.loc[
    (
        df["observation_name"] ==
        "Hemoglobin A1c/Hemoglobin.total in Blood"
    ) &
    (df["valueQuantity.value"] >= 6.5),
    "diabetes_risk"
] = "Diabetic"

df.loc[
    (
        df["observation_name"] ==
        "Hemoglobin A1c/Hemoglobin.total in Blood"
    ) &
    (df["valueQuantity.value"] >= 5.7) &
    (df["valueQuantity.value"] < 6.5),
    "diabetes_risk"
] = "Prediabetic"

df.loc[
    (
        df["observation_name"] ==
        "Hemoglobin A1c/Hemoglobin.total in Blood"
    ) &
    (df["valueQuantity.value"] < 5.7),
    "diabetes_risk"
] = "Normal"

In [ ]:
df.head()

,id,status,effectiveDateTime,resourceType,code.coding,subject.reference,encounter.reference,valueQuantity.value,valueQuantity.unit,valueQuantity.system,...,year,month,month_name,loinc_code,observation_name,systolic_bp,diastolic_bp,bmi_category,high_bp_flag,diabetes_risk
0,cab2e694-f24b-4409-a71e-8e109b5229bb,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '4548-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,5.90000,%,http://unitsofmeasure.org/,...,2012.0,12.0,December,4548-4,Hemoglobin A1c/Hemoglobin.total in Blood,NaN,NaN,None,0,Prediabetic
1,0017cb31-e3b5-4167-a513-c0e99a1e8056,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '8302-...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,174.66385,cm,http://unitsofmeasure.org/,...,2012.0,12.0,December,8302-2,Body Height,NaN,NaN,None,0,None
2,a11dcfea-83a0-4588-b60e-62f8dc437512,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '29463...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,97.46566,kg,http://unitsofmeasure.org/,...,2012.0,12.0,December,29463-7,Body Weight,NaN,NaN,None,0,None
3,ef407614-d461-4e7d-b48a-e68165b66580,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '39156...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,31.94814,kg/m2,http://unitsofmeasure.org/,...,2012.0,12.0,December,39156-5,Body Mass Index,NaN,NaN,Obese,0,None
4,5a54a97c-67bc-46f4-8619-81971eceaabc,final,2012-12-28 17:22:02-05:00,Observation,"[{'system': 'http://loinc.org', 'code': '55284...",urn:uuid:99937389-654f-4a48-8e74-ac81cf260e0f,urn:uuid:c721f18e-4f6d-4e1d-a496-9de28fade1cf,NaN,NaN,NaN,...,2012.0,12.0,December,55284-4,Blood Pressure,159.0,104.0,None,1,None

In [ ]:
df.columns = [

    col.replace(".", "_")
       .replace(" ", "_")
       .lower()

    for col in df.columns
]

In [ ]:
df.columns

Index(['id', 'status', 'effectivedatetime', 'resourcetype', 'code_coding',
       'subject_reference', 'encounter_reference', 'valuequantity_value',
       'valuequantity_unit', 'valuequantity_system', 'valuequantity_code',
       'component', 'valuecodeableconcept_coding', 'observation_date', 'year',
       'month', 'month_name', 'loinc_code', 'observation_name', 'systolic_bp',
       'diastolic_bp', 'bmi_category', 'high_bp_flag', 'diabetes_risk'],
      dtype='object')

In [ ]:
dashboard_df = df[
    [
        'id', 'status', 'effectivedatetime', 'resourcetype', 'code_coding',
       'subject_reference', 'encounter_reference', 'valuequantity_value',
       'valuequantity_unit', 'valuequantity_system', 'valuequantity_code',
       'component', 'valuecodeableconcept_coding', 'observation_date', 'year',
       'month', 'month_name', 'loinc_code', 'observation_name', 'systolic_bp',
       'diastolic_bp', 'bmi_category', 'high_bp_flag', 'diabetes_risk'
    ]
]


# Remove empty observation rows
dashboard_df = dashboard_df.dropna(
    subset=["observation_name"]
)

In [ ]:
output_file = "looker_ready_healthcare_dataset.csv"

dashboard_df.to_csv(
    output_file,
    index=False
)

print("\nCleaned Dataset Shape:", dashboard_df.shape)

print("\nCSV Exported Successfully:")
print(output_file)

Cleaned Dataset Shape: (5134, 24)

CSV Exported Successfully:
looker_ready_healthcare_dataset.csv